### ISSUE TITLE
MacOS: Could not find Husky path

### ISSUE THREAD

**Issue by StefanGreve** [alirezanet/Husky.Net#126]
### Version

0.7.1

### Details

I have used Husky.Dotnet in various projects in the past, but so far only on Windows. However, I recently switched to MacOS for my development environment and noticed that none of my hooks work anymore. The hooks fail silently if used indirectly via `pre-commit`, and fail explicitly with this error message when executed directly through the `dotnet run` command. 

```
[Husky] 🚀 Loading tasks ...
failed to execute command 'git'
Could not find Husky path
```

From my perspective, it looks like there's some extra configuration for MacOS missing?

Other things I have tried:

- Run this command in different shells (`pwsh`, `bash`, `zsh`)
- Ensured that `git` is in PATH
- Set file permission for executing hooks `chmod +x ./.husky/pre-commit`
- Reduce the error to husky itself (i.e. run a simple `echo` command for test purposes)

There's a slightly newer version of this project that I also tried to update to, but with no different results, which is why I am reporting this error with the version I first encountered it on.

### Steps to reproduce

- On MacOS, follow the steps described in the [official guide](https://alirezanet.github.io/Husky.Net/guide/getting-started.html#setup-husky-for-your-project)
- Configure `task-runner.json` with

```json
{
   "$schema": "https://alirezanet.github.io/Husky.Net/schema.json",
   "tasks": [
      {
         "name": "test",
         "group": "",
         "command": "echo",
         "args": [
            "hello, world!"
         ]
      }
    ]
}
```

**Comment by StefanGreve** [comment]
After looking at the source code, I noticed that his error only occurs when `husky.sh` could not be located by the dotnet tool. I remembered seeing this file in the `.husky` folder, but not on the cloned repository. 

After connecting the dots I concluded that this must have happened because the `.husky/_/husky.sh` file was not tracked by the version history of the project. It can be re-generated with the `dotnet husky install` command. After that everything worked again smoothly.

I think some further guidance in the documentation would be much appreciated (e.g. should the files in the `_` folder be ignored? >> Possibly, personally I took the discard character in the name as a nudge to dismiss this folder from history; but then this project should emphasize the need for collaborators to run `dotnet husky install` after the `dotnet tool restore` command).

Suggestion: If it is possible, the tool should try to run the `dotnet husky install` command itself automatically if the `./husky/_` doesn't exist.

**Comment by alirezanet** [comment]
Hi @StefanGreve,
>After looking at the source code, I noticed that his error only occurs when husky.sh could not be located by the dotnet tool. I remembered seeing this file in the .husky folder, but not on the cloned repository.
After connecting the dots I concluded that this must have happened because the .husky/_/husky.sh file was not tracked by the version history of the project. It can be re-generated with the dotnet husky install command. After that everything worked again smoothly.

Yes, We have to re-generate it the first time, that's the main reason the `husky install` exists. 

> I think some further guidance in the documentation would be much appreciated (e.g. should the files in the _ folder be ignored?

Contributing to documentation is really easy. You can just go to the documentation and click on the `Help us improve this page` button, and since you were dealing with this problem directly, feel free to make your desired changes. After all, this is an open-source project. also feel free to add additional menus/pages if needed.

>Suggestion: If it is possible, the tool should try to run the dotnet husky install command itself automatically if the ./husky/_ doesn't exist.

it is not possible because without the `husky.sh` file, husky won't run automatically. it is a chicken and egg situation ... we're using this file to link the hooks to the husky executable. 

---

thanks for all the feedback 🙏, should we close this bug then?

**Comment by StefanGreve** [comment]
> thanks for all the feedback 🙏, could we close this bug then?

Yeah, sure.
