### ISSUE TITLE
Improve CSX execution time

### ISSUE THREAD

**Issue by alirezanet** [alirezanet/Husky.Net#28]
### Details

Currently, CSX execution is not so efficient it takes about 2 seconds on the first run which is not ideal, I opened this issue to evaluate possible options to solve this problem. the expected behavior is to minimize the Roslyn compiler warming up process. 

the minimum execution time for the bellow command currently is about 1-2 seconds.
```
dotnet husky exec <fileNme.csx>
```

**Comment by acesyde** [comment]
Hi @alirezanet 

IMO you can try to compile scripts when you detect a change and only execute them when it's required, you can minimize the execution process time

I don't know if it's possible it's just an idea 😄

**Comment by alirezanet** [comment]
> Hi @alirezanet
> 
> IMO you can try to compile scripts when you detect a change and only execute them when it's required, you can minimize the execution process time by doing this
> 
> I don't know if it's possible it's just an idea 😄

Hi, Thank you for the suggestion, I agree. Compiling scripts probably is the best solution that comes to mind but I didn't find any documentation of Roslyn APIs that can be used yet although I didn't spend enough time searching.

**Comment by Xemrox** [comment]
Heya. Joining the discussion.
More concrete solution would involve a hash that relates to the source.
Something like $script.csx -> $script.$hash.dll?
Btw writing the assembly to a file can be done with:
`compilation.Emit(...)`

**Comment by acesyde** [comment]
I have checked it quickly

```cs
var cachePath = System.IO.Path.Combine(workingDirectory, ".cache");
var ouputDllPath = System.IO.Path.Combine(cachePath, "output.dll");
var outputPdbPath = System.IO.Path.Combine(cachePath, "output.pdb");

if (!Directory.Exists(cachePath))
{
    Directory.CreateDirectory(cachePath);
}

if (File.Exists(ouputDllPath) && File.Exists(outputPdbPath))
{
         using var ilstream = new MemoryStream();
         using var pdbstream = new MemoryStream();
         using var ouputDllPathStream = new FileStream(ouputDllPath, FileMode.Open);
         ouputDllPathStream.CopyTo(ilstream);
         using var outputPdbPathStream = new FileStream(outputPdbPath, FileMode.Open);
         outputPdbPathStream.CopyTo(pdbstream);

         var assembly = Assembly.Load(ilstream.GetBuffer(), pdbstream.GetBuffer());
         var type = assembly.GetType("Submission#0");
         var factory = type.GetMethod("<Factory>");
         var submissionArray = new object[2];
         var task = (Task<object>)factory.Invoke(null, new object[] { submissionArray });
         await task;
         "Command executed.".Log(ConsoleColor.Green);
         return;
}
else
{
         using var ouputDllPathStream = new FileStream(ouputDllPath, FileMode.OpenOrCreate);
         using var outputPdbPathStream = new FileStream(outputPdbPath, FileMode.OpenOrCreate);
         var emitResult = compilation.Emit(ouputDllPathStream, outputPdbPathStream);
}
```

It seems to be better, but I need to spend more time to benchmark it 😄 

![image](https://user-images.githubusercontent.com/958435/156046655-65dcb4c0-2254-47f1-ab1e-b8d69b9eab64.png)

Thks for the idea @Xemrox

**Comment by alirezanet** [comment]
Interesting ...  I think we don't need a global cache folder and we can use `.husky\_` folder to store the compiled cache files also we can save the files using its hash (crc32 or md5) as fileNames to keep track of changes. but this solution needs a cleanup command.

**Comment by Xemrox** [comment]
@acesyde why do you copy the `FileStream `to a `MemoryStream`? You could make use of `Assembly.LoadFile(absolutePath)` instead.
@alirezanet sha512 is the standard for hashes so go for that instead of md5. My proposal is a $scriptName.hash file containing the hash of the source that lead to the latest assembly. This way if the hash differs you can safely assume the assembly is out of sync and regenerate it

**Comment by acesyde** [comment]
@Xemrox  When I said fast it was fast, now it's time to clean up and improve 😃

**Comment by alirezanet** [comment]
@Xemrox  what do you mean by SHA512 is standard?  
In our case using SHA algorithms is unnecessary because they are slower and more CPU intensive than something like crc32 or md5.  the thing is we don't need a secure hash algorithm here. anything with a checksum works fine. 
but when we implemented this feature we can do some benchmarking. 

![image](https://user-images.githubusercontent.com/7004080/156141932-68e3b197-7dec-4634-8b54-15833e9c778e.png)

**Comment by acesyde** [comment]
@alirezanet with benchmarkdotnet

![image](https://user-images.githubusercontent.com/958435/156152696-f5d4ebe6-fddc-4e6a-a212-9d8576eece4a.png)

**Comment by alirezanet** [comment]
Nice. I'm not sure it performs better but can you include also `[Crc32.NET](https://github.com/force-net/Crc32.NET)`? because here we just care about performance. It could be faster.

**Comment by acesyde** [comment]
Not a huge difference, IMO using the official cryptographic library instead of an external lib may be better for the future

|     Method |     Mean |     Error |    StdDev | Ratio |  Gen 0 | Allocated |
|----------- |---------:|----------:|----------:|------:|-------:|----------:|
|  TestCRC32 | 5.605 us | 0.2339 us | 0.6822 us |  1.00 | 0.0610 |     386 B |
|    TestMd5 | 5.992 us | 0.1182 us | 0.1407 us |  1.00 | 0.0610 |     426 B |
|   TestSHA1 | 6.089 us | 0.1216 us | 0.1623 us |  1.00 | 0.0687 |     450 B |
| TestSHA256 | 6.340 us | 0.1250 us | 0.2848 us |  1.00 | 0.0763 |     490 B |
| TestSHA512 | 8.064 us | 0.1564 us | 0.2193 us |  1.00 | 0.2289 |   1,453 B |

```
// * Warnings *
MultimodalDistribution
  HashBench.TestCRC32: .NET 6.0 -> It seems that the distribution is bimodal (mValue = 3.86)
```

**Comment by Xemrox** [comment]
We are responsible to avoid collision attacks. It's not about the performance of md5 vs sha512. If you hash the code and compile the assembly we must be sure to execute it only if the source matches our fingerprint of that assembly. Thinking further we only store a source fingerprint and no assembly fingerprint that relates to that... Am 01.03.2022 10:26 schrieb AliReZa Sabouri ***@***.***>:
@Xemrox  what do you mean by SHA512 is standard?
In our case using SHA algorithms is unnecessary because they are slower and more CPU intensive than something like crc32 or md5.  the thing is we don't need a secure hash algorithm here. anything with a checksum works fine.
but when we implemented this feature we can do some benchmarking.

**Comment by alirezanet** [comment]
I get your point but even hashes like SHA-256 are SHA-512 are not collision-free, also in our case the source code (CSX) is available for the attackers and we don't share or commit compiled versions anywhere. so IMO **thinking about security** is a little bit over-engineering.  let's say you wanna somehow attack this system, how it is possible when you don't have any access to other contributors' **compiled files**. I'm not saying using SHA-512 is a bad choice, on the contrary, I personally have a strong interest in safer algorithms but I don't see any real-world vulnerabilities yet. 
But to show my respect to your opinion about this I'll probably use SHA-512 since its compilation overhead is barely noticeable.

**Comment by alirezanet** [comment]
You both voted for SHA-512, hands up 🙌 😉.  so SHA-512 it is.  😅

**Comment by acesyde** [comment]
But in the case of "pre-commit" they use an external database (sqlite) to store all this information

**Comment by alirezanet** [comment]
What do you think about the default behavior? should `exec` command automatically compile the scripts for future executions? or we should add an option like `--compile` to change its behavior? In the end, we need one of these options probably `--raw` or  `--compile`

**Comment by acesyde** [comment]
So i made a benchmark between compiled vs actual solution and the compiled version is so a little bit faster 🤣 

|            Method |         Mean |      Error |     StdDev | Ratio |   Allocated |
|------------------ |-------------:|-----------:|-----------:|------:|------------:|
|   UseCSharpScript | 29,607.01 us | 548.193 us | 457.766 us | 1.000 | 6,404,152 B |
| UseCompiledScript |     78.44 us |   1.516 us |   2.269 us | 0.003 |       768 B |

**Comment by alirezanet** [comment]
added in `v0.5.0`.
