### ISSUE TITLE
${staged} variable contains some temporary files

### ISSUE THREAD

**Issue by ultrr** [alirezanet/Husky.Net#39]
### Version

0.4.0

### Details

I was running a git hook with several steps configured. I was expecting only REAL staged files to be committed but unfortunately there were some additional staged files which shouldn't be added to ${staged} variable.

### Steps to reproduce

1. dotnet new tool-manifest
2. dotnet tool install JetBrains.ReSharper.GlobalTools
3. dotnet tool install ReGitLint
4. dotnet tool install Husky
5. configure Husky, using following `task-runner.json`
```json
{
  "tasks": [
    {
      "name": "before - echo staged from husky",
      "command": "echo",
      "args": ["${staged}"]
    },
    {
      "name": "reglint",
      "command": "dotnet",
      "args": ["regitlint", "-f", "staged", "--jb", "--verbosity=WARN"]
    },
    {
      "name": "after - echo staged from husky",
      "command": "echo",
      "args": ["${staged}"]
    },
    {
      "name": "after - echo staged from git",
      "command": "git",
      "args": ["diff", "--name-only", "--cached"]
    },
    {
      "name": "after - echo staged from ???",
      "command": "git",
      "args": ["diff-index", "--cached", "--diff-filter=AM", "--no-renames", "--name-only", "HEAD"]
    }
  ]
}
```
6. as you can see in git log output, echo of ${staged} variable includes other (temporary?) files, while those files aren't included while running git diff/diff-index commands manually. In our use case, we want to run `git add ${staged}` after `regitlint` but it results in committing those temporary files as well.

**Comment by alirezanet** [comment]
I don't totally understand what is the problem!? Since husky doesn't change the file states.  
how do you add your files to git in the first place (staging step)? Your reproducible example doesn't do anything because nothing is staged yet.
![image](https://user-images.githubusercontent.com/7004080/157482455-dd45420a-0425-4a23-8f43-73d3b5b8b50e.png)

also, I've tried `git add test.txt` to stage a file:
![02](https://user-images.githubusercontent.com/7004080/157484660-2fb6de20-25d7-4589-aa27-31367b63e992.jpg)

everything was normal except weird behavior from reglint tool (I have no idea why it is scanning my entire system and found a different project !)

**Comment by ultrr** [comment]
My bad! Forgot to include the output.
Managed to recreate the issue on a fresh solution, with usage of Husky.Net only.

Link to the repo: https://github.com/ultrr/husky.net-staged-bug

Steps to reproduce:
1. Clone the repo
2. Restore the solution: `dotnet restore`
3. Change the content of file1.txt: `echo someContent123 >> file1.txt`
4. Change the content of file2.txt. Has to be different from file1.txt: `echo someOtherContent123 >> file2.txt`
5. Stage both files: `git add file1.txt file2.txt`
6. Commit the changes: `git commit -m "test"`

Output:
```
[Husky] 🚀 Loading tasks ...
--------------------------------------------------
[Husky] ⚡ Preparing task 'before-echo-staged'
[Husky] ⌛ Executing task 'before-echo-staged' ...
file1.txt file2.txt
[Husky]  ✔ Successfully executed in 2ms
--------------------------------------------------
[Husky] ⚡ Preparing task 'cp'
[Husky] ⌛ Executing task 'cp' ...
[Husky]  ✔ Successfully executed in 9ms
--------------------------------------------------
[Husky] ⚡ Preparing task 'after-echo-staged'
[Husky] ⌛ Executing task 'after-echo-staged' ...
file1.txt 26c27_file2.txt file2.txt
[Husky]  ✔ Successfully executed in 1ms
--------------------------------------------------
[Husky] ⚡ Preparing task 'git'
[Husky] ⌛ Executing task 'git' ...
[Husky]  ✔ Successfully executed in 8ms
--------------------------------------------------
[master 059d397] test
 3 files changed, 3 insertions(+), 2 deletions(-)
 create mode 100644 63c0e_file2.txt
```

`git status` output:
```
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    63c0e_file2.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by alirezanet** [comment]
Hi, Thank you for the repo
because in this case, you want to control git indexing situation to prevent husky interference I've added a new option `-p` to the run command that you can use in `v0.4.2`:

![image](https://user-images.githubusercontent.com/7004080/157539880-cef7f01f-0414-4ffc-8f2e-83d048d8e8a0.png)

So you just need to update your run command to:
``` shell
dotnet husky run -p
```

![image](https://user-images.githubusercontent.com/7004080/157539051-6769cb03-9c81-4313-9575-c3d45169a2a7.png)
